spring:  
  profiles:
    active: dev
---  
server:
  port: 8001
spring: 
  profiles: dev
  application: 
    name: kj-bps-common
  datasource:  
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false 
  task: 
    pool: 
      corePoolSize: 10
      maxPoolSize: 50
      keepAliveSeconds: 1000
      queueCapacity: 300
      
mybatis:
  type-aliases-package: com.bpaas.bps.commons.po
  mapper-locations: classpath:com.bpaas.bps.commons.mapper/*.xml